Case studies SVM in python
First we will try and implement an SVm model in python. We will take a social network dataset which  contains features 
such as age and salary of a person to predict whether they purchased the procdur or not 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing,neighbors,svm

In [2]:
df = pd.read_csv("C:\\Users\\GOURAV NEGI\\Downloads\\Social_Network_Ads.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
x = df.iloc[:,[2,4]].values
y = df.iloc[:,4].values

Now we will  the data info training and testing.We will take 75% of the data for training and test it on the rest 
which makes 25%

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 25, random_state = 0)

#After spitting we will scale the feature to expect normal distribution of the data.We will use
Standard Scaler in this case.

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Now the preprocessing of the data is over.it is time to build the model.We will apply three kernel tricks in this case
and try evaluating the 

Type Markdown and LaTeX: a square

In [28]:
from sklearn.svm import SVC

#we have built our first model Now we will predict our data.

In [29]:
classifier_linear = SVC(kernel = 'linear', random_state = 0)
classifier_linear.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [30]:
y_pred_linear = classifier_linear.predict(x_test)
y_pred_linear

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0], dtype=int64)

In [31]:
classifier_poly = SVC (kernel = 'poly', random_state = 0)
classifier_poly.fit(x_train, y_train)
y_pred_poly = classifier_poly.predict(x_test)

In [38]:
classifier_poly = SVC (kernel = 'poly', random_state = 0)
classifier_poly.fit(x_train, y_train)
y_pred_rbf = classifier_poly.predict(x_test)

#We have made on three Kernels.The performance will be evaluated on the basis of confusion matrix and classification report.

In [39]:
from sklearn.metrics import confusion_matrix

#Confusion matrix for linear kernel

In [40]:
cm_linear = confusion_matrix(y_test, y_pred_linear)
cm_linear

array([[21,  0],
       [ 0,  4]], dtype=int64)

Confusion atrix for polynominal kernel

In [41]:
cm_poly = confusion_matrix(y_test,y_pred_poly)
cm_poly

array([[21,  0],
       [ 0,  4]], dtype=int64)

Confusion matrix for RBF kernel

In [42]:
cm_rbf = confusion_matrix(y_test, y_pred_rbf)
cm_rbf

array([[21,  0],
       [ 0,  4]], dtype=int64)

 Classification report Classification report is an extended metric of  confusion matrix which gives an idea about precission
    and recall.it tells  model is and the exact accuracy of our model.

Classification report on linear kernel 

In [45]:
from sklearn.metrics import classification_report

In [46]:
class_report_linear = classification_report(y_test, y_pred_linear)
print(class_report_linear)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00         4

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25



# precision

precision is the ability of a classifier not to label an instance positive that is actually negative.
For each class, it is defined as the ratio of true positives to the sum of a true of a true positive and false 
positive. precision:- Accuracy of positive predictions.

# Recall:

Recall is a measure of the classifiers completeness; the ability of a classifier to correctly find all positive instance. 
For each class, it is defined as the ratio of true positives to the sum of true positives and false negatives.

# f1-score :

The F1 score is a weighted harmonic mean of precision and recall such that the best score is 1.0 and
the worst is 0.0. F1 score are lower than accuracy measures as they embed precision and recall into
their computation.

What Is a Harmonic Mean? The harmonic mean is a type of numerical average. It is calculated by dividing
the number of observation by the reciprocal of each number in the series. Thus, the harmonic mean is 
the reciprocal of the arithmetic mean of the reciprocals.

# Mathematics
an expression or function so related to another that their product is unity; the quantity obtained by divide the number 
one by a given quantity.

# Support:

Support is the number of actual occurrences of the class in the specified dataset.
Imbalanced support in the training data may indicate structural weaknesses in the reported scores 
of the classifier and could indicate the need for stratified sampling or rebalancing.

The support is the number of sample of the true response that lie in that class.

# Recall:

The ability of a model to find all the relevant cases within a data set. Mathematically, We define recall as the number
of true positive divided by the number of true positive plus the number of false negatives.

Precision: The ability of a classification model to identify only the relevant data points.
Mathematically, precision the number of true positives divided by the number of true positives plus the 
number of false positives.