In [1]:
import numpy as np 
import pandas as pd


In [2]:
df = pd.read_csv("C:\\Users\\GOURAV NEGI\\Downloads\\Copy of Copy of fifa_data.csv",index_col=[0])

In [3]:
df.shape

(18207, 88)

In [4]:
df.shape[0]

18207

In [5]:
#this formula is clean the data in seconds

In [6]:
for i in df:
    if df[i].isnull().any():
        print(i,'.......',df[i].isnull().sum()/df.shape[0]*100)
       #print('{}..........{}'.format(i,df[i].isnull().sum()/df.shape[0]*(100)))

Club ....... 1.323666721590597
Preferred Foot ....... 0.26363486571099026
International Reputation ....... 0.26363486571099026
Weak Foot ....... 0.26363486571099026
Skill Moves ....... 0.26363486571099026
Work Rate ....... 0.26363486571099026
Body Type ....... 0.26363486571099026
Real Face ....... 0.26363486571099026
Position ....... 0.32954358213873786
Jersey Number ....... 0.32954358213873786
Joined ....... 8.529686384357664
Loaned From ....... 93.05761520294392
Contract Valid Until ....... 1.5873015873015872
Height ....... 0.26363486571099026
Weight ....... 0.26363486571099026
LS ....... 11.451639479321141
ST ....... 11.451639479321141
RS ....... 11.451639479321141
LW ....... 11.451639479321141
LF ....... 11.451639479321141
CF ....... 11.451639479321141
RF ....... 11.451639479321141
RW ....... 11.451639479321141
LAM ....... 11.451639479321141
CAM ....... 11.451639479321141
RAM ....... 11.451639479321141
LM ....... 11.451639479321141
LCM ....... 11.451639479321141
CM ....... 11.45163

In [7]:
df.isnull().sum().sum()

76984

In [8]:
import numpy as np
a = np.ones((5,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
b=np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
a[:]

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# cleaning data formula 

In [13]:
for i in df:
    if df[i].isnull().any():
        
        if df[i].dtype==float:
            if df[i].mean()-df[i].median()<10:
                
                df[i].fillna(df[i].mean(),inplace=True)
            else:
                df[i].fillna(df[i].median(),inlace=True)
                
        elif df[i].dtype=='object':
            df[i].fillna(df[i].mode()[0],inplace=True)

In [14]:
df.isnull().sum().sum()

0